import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, Check, CreditCard, MapPin, Phone, ShieldCheck } from "lucide-react";
import { AppointmentForm, BeforeAfter, BlogSection, DoctorsSection, Emergency, FAQ, ServicesSection, Testimonials } from "@/components/home";
import { Reveal } from "@/components/motion";
import { clinic } from "@/lib/data";

const pages: Record<string,{title:string; eyebrow:string; intro:string}> = {
  about:{title:"Dentistry designed around your family.",eyebrow:"About Dr. Shaheen's Dental Clinic",intro:"A trusted Habra clinic focused on emergency care, family dentistry, clear guidance and lasting patient relationships."},
  services:{title:"Complete care for every smile.",eyebrow:"Our services",intro:"Preventive, restorative, cosmetic and emergency dentistry delivered with precision and genuine care."},
  doctors:{title:"Meet the people behind your care.",eyebrow:"Our doctors",intro:"Experienced clinicians, shared standards and one commitment: treating you like a person, not a procedure."},
  treatments:{title:"Modern treatments. Thoughtful outcomes.",eyebrow:"Advanced treatments",intro:"Clear plans, digital precision and comfort-focused techniques for results that look and feel natural."},
  gallery:{title:"Real smiles, beautifully restored.",eyebrow:"Before & after",intro:"Explore considered transformations created for health, harmony and individual confidence."},
  appointment:{title:"Your healthier smile starts here.",eyebrow:"Book an appointment",intro:"Tell us what you need and our patient care team will find the right appointment for you."},
  reviews:{title:"Care people feel good talking about.",eyebrow:"Patient reviews",intro:"Patient experiences with Dr. Shaheen's approach to comfort, oral health and confidence."},
  blog:{title:"Practical advice for lifelong oral health.",eyebrow:"Dental tips & insights",intro:"Clear, useful guidance from our clinicians—without the jargon."},
  contact:{title:"Let’s make your next visit easy.",eyebrow:"Contact Dr. Shaheen's",intro:"Questions or ready to book? Visit Dr. Shaheen's Dental Clinic in Habra."},
};
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params; return {title:pages[slug]?.eyebrow??"Dental Care"}}

function PageHero({data}:{data:typeof pages[string]}) {
  return <section className="relative overflow-hidden bg-[radial-gradient(circle_at_80%_20%,#d8f5f1,transparent_34%),linear-gradient(135deg,#fbfcfa,#edf9f9)] py-24 md:py-32"><div className="container"><Reveal><span className="eyebrow">{data.eyebrow}</span><h1 className="mt-7 max-w-5xl font-[var(--font-heading)] text-[clamp(3.3rem,7vw,6.8rem)] font-semibold leading-[.96] tracking-[-.05em]">{data.title}</h1><p className="lead mt-7 max-w-2xl">{data.intro}</p></Reveal></div></section>
}

export default async function Page({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params; const data=pages[slug]; if(!data)notFound();
  return <><PageHero data={data}/>{slug==="about"&&<About/>}{slug==="services"&&<><ServicesSection all/><Emergency/></>}{slug==="doctors"&&<><DoctorsSection all/><Values/></>}{slug==="treatments"&&<Treatments/>}{slug==="gallery"&&<><BeforeAfter/><GalleryGrid/></>}{slug==="appointment"&&<Appointment/>}{slug==="reviews"&&<><Testimonials all/><FAQ/></>}{slug==="blog"&&<BlogSection all/>}{slug==="contact"&&<Contact/>}</>;
}

function About(){return <><section className="section"><div className="container grid gap-12 lg:grid-cols-2"><Reveal><span className="eyebrow">Our philosophy</span><h2 className="section-title mt-5">Modern care should still feel personal.</h2></Reveal><Reveal><p className="lead">Dr. Shaheen&apos;s Dental Clinic brings emergency, preventive, cosmetic, paediatric and surgical dentistry together at one convenient location in Habra.</p><p className="lead mt-5">Every recommendation is explained clearly, every option is considered carefully, and treatment is planned around your oral health needs.</p></Reveal></div></section><Values/><section className="section"><div className="container grid gap-6 md:grid-cols-3">{[["10","listed dental services"],["11:30 pm","closing time"],["Habra","clinic location"]].map(([a,b])=><div className="card p-8" key={a}><b className="font-[var(--font-heading)] text-5xl text-[var(--teal)]">{a}</b><p className="mt-3 text-[var(--ink-soft)]">{b}</p></div>)}</div></section></>}
function Values(){return <section className="section section-soft"><div className="container"><div className="grid gap-5 md:grid-cols-3">{[["Clinical integrity","We recommend only what supports your health and goals."],["Comfort by design","From the environment to the technique, calm is intentional."],["Clarity always","Plans, costs and expectations are transparent from the start."]].map(([a,b],i)=><Reveal key={a} delay={i*.05}><div className="card h-full p-8"><span className="grid h-12 w-12 place-items-center rounded-full bg-[var(--cyan)] font-bold text-[var(--teal)]">0{i+1}</span><h3 className="mt-8 text-2xl font-semibold">{a}</h3><p className="mt-4 leading-7 text-[var(--ink-soft)]">{b}</p></div></Reveal>)}</div></div></section>}
function Treatments(){return <><ServicesSection all/><section className="section section-soft"><div className="container grid gap-12 lg:grid-cols-2"><Reveal><span className="eyebrow">How care works</span><h2 className="section-title mt-5">A clear path from concern to confidence.</h2></Reveal><div className="grid gap-4">{["Listen & diagnose","Plan together","Treat with precision","Support for the long term"].map((x,i)=><Reveal key={x} delay={i*.05}><div className="card flex items-center gap-5 p-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[var(--teal)] text-sm font-bold text-white">{i+1}</span><b className="text-lg">{x}</b></div></Reveal>)}</div></div></section></>}
function GalleryGrid(){return <section className="section"><div className="container"><div className="grid gap-5 md:grid-cols-2">{["Whitening","Ceramic veneers","Clear aligners","Implant restoration"].map((x,i)=><div key={x} className={`aspect-[16/10] rounded-[30px] p-7 ${["bg-[#d7f0eb]","bg-[#ede8dc]","bg-[#dfeaf1]","bg-[#e5f1ec]"][i]} flex items-end`}><div><small className="font-bold uppercase tracking-[.12em] text-[var(--teal)]">Case 0{i+1}</small><h3 className="mt-2 text-3xl font-semibold">{x}</h3><p className="mt-2 text-sm text-[var(--ink-soft)]">Individual results vary. Shared with patient consent.</p></div></div>)}</div></div></section>}
function Appointment(){return <section className="section"><div className="container grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><span className="eyebrow">What happens next</span><div className="mt-7 grid gap-5">{["Submit your preferred details","Clinic team confirms availability","Receive appointment instructions"].map((x,i)=><div key={x} className="flex gap-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[var(--cyan)] text-sm font-bold text-[var(--teal)]">{i+1}</span><p className="pt-1 font-semibold">{x}</p></div>)}</div><div className="mt-10 rounded-3xl bg-[var(--ink)] p-6 text-white"><Phone size={21}/><b className="mt-4 block">Need direct contact details?</b><p className="mt-2 text-sm text-white/60">Open the clinic listing for the latest phone and direction information.</p></div></div><AppointmentForm/></div></section>}
function Contact(){return <><section className="section"><div className="container grid gap-10 lg:grid-cols-2"><Reveal><div className="card p-8"><MapPin className="text-[var(--teal)]"/><h2 className="mt-6 text-3xl font-semibold">{clinic.name}</h2><p className="mt-4 leading-7 text-[var(--ink-soft)]">{clinic.address}</p><p className="mt-3 text-sm font-semibold text-[var(--teal)]">{clinic.hoursDisplay}</p><div className="mt-7 grid gap-3 text-sm"><a className="font-bold text-[var(--teal)]" href={clinic.phoneHref} target="_blank" rel="noreferrer">{clinic.phoneDisplay}</a><a href={clinic.mapLink} target="_blank" rel="noreferrer">Open in Google Maps</a></div></div></Reveal><Reveal><div className="h-[430px] overflow-hidden rounded-[30px] bg-[var(--cyan)] shadow-[var(--shadow)]"><iframe className="h-full w-full border-0" title="Map showing Dr. Shaheen's Dental Clinic in Habra" loading="lazy" referrerPolicy="no-referrer-when-downgrade" src={clinic.mapEmbed}/></div></Reveal></div></section><section className="section section-soft"><div className="container grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><span className="eyebrow">Send an enquiry</span><h2 className="section-title mt-5">How can we help?</h2></div><AppointmentForm compact/></div></section><Insurance/></>}
function Insurance(){return <section className="section"><div className="container grid gap-5 md:grid-cols-2"><div className="card p-8"><ShieldCheck className="text-[var(--teal)]"/><h3 className="mt-5 text-2xl font-semibold">Treatment guidance</h3><p className="mt-3 leading-7 text-[var(--ink-soft)]">The Dr. Shaheen&apos;s team explains suitable treatment options and the expected care process before you proceed.</p></div><div className="card p-8"><CreditCard className="text-[var(--teal)]"/><h3 className="mt-5 text-2xl font-semibold">Payment information</h3><p className="mt-3 leading-7 text-[var(--ink-soft)]">Contact the clinic directly for current treatment fees and available payment options.</p></div></div></section>}
